# IcarusEye v2
networks:
  icaruseye:
    driver: bridge

volumes:
  redis_data:

services:

  redis:
    image: redis:7-alpine
    container_name: icaruseye-redis
    restart: unless-stopped
    networks:
      - icaruseye
    volumes:
      - redis_data:/data
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  pipeline:
    build:
      context: .
      dockerfile: docker/pipeline/Dockerfile
    container_name: icaruseye-pipeline
    restart: unless-stopped
    networks:
      - icaruseye
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - "5100"   # raw frame server
      - "5101"   # annotated frame server
    runtime: nvidia                          
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all           
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs:ro
      - ./sample:/app/sample:ro
      - ./models:/app/models
    devices:
      - /dev/v4l2-nvdec:/dev/v4l2-nvdec
      - /dev/v4l2-nvenc:/dev/v4l2-nvenc
      - /dev/nvhost-nvdec:/dev/nvhost-nvdec
  #   - /dev/icaruseye/capture0:/dev/capture0

  tower:
    build:
      context: .
      dockerfile: docker/tower/Dockerfile
    container_name: icaruseye-tower
    restart: unless-stopped
    networks:
      - icaruseye
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PIPELINE_HOST=pipeline
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs:ro
      - ./pipeline/tower/static:/app/pipeline/tower/static